
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models


name: snowflake_dbt1_projecte
version: 1.0

profile: snowflake_dbt1_projecte

models:
  ecommerce_dbt_project:
    staging:
      materialized: view
    intermediate:
      materialized: ephemeral
    marts:
      materialized: table